# Generated by Django 2.2.2 on 2019-07-13 01:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyfreshgoods', '0001_initial'),
        ('dailyfreshuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsBrowser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='浏览时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyfreshgoods.GoodsInfo', verbose_name='商品ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyfreshuser.UserInfo', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '用户浏览记录',
                'verbose_name_plural': '用户浏览记录',
            },
        ),
    ]
